### PR TITLE
Switch to coursier 1.0.0-M11

### PR DESCRIPTION
**Pull request by alexarchambault**
I couldn't have libisabelle use coursier by following the instructions in the README it seems, so I wasn't able to test that directly.

### CODE REVIEW

**Comment by larsrh** [comment]
Thanks for the pull request, but …

> I couldn't have libisabelle use coursier by following the instructions in the README it seems, so I wasn't able to test that directly.

… I don't understand this part. If you mean testing that file downloading actually works, yes, this is currently untested.

**Comment by alexarchambault** [comment]
I just meant that the coursier code didn't seem to have run on a fresh install, by just following the README. (Admittedly, I may have been wrong, I could have a look at it again.)

**Comment by larsrh** [comment]
The code definitely runs, but it will hit the local Ivy2 repository instead of downloading anything. Anyway, tests for downloading are pending, but this one is good to go. Thanks :sparkles:

**Comment by alexarchambault** [comment]
Of course... :sweat_smile:

**Comment by larsrh** [comment]
I misspoke. The code definitely does get exercised, as can be witnessed from the Travis build output. It's just not guaranteed – if everything's in the local cache, nothing happens.

**Pull request merged**
